### ISSUE TITLE
titanic v1

### ISSUE THREAD

**Issue by echna** [gindeleo/machine_learning1#2]
Trying out the issue feature
1. figure out how to sync it with files on laptop, so I can work with my own text editor
2. clean up the data
3. do some machine learning on the data
4. complain that the numbering system is not working properly

**Comment by gindeleo** [comment]
1. What numbering system? Do you mean version control? 

Git manages that for you no need to name something v1. Just make branches for new features and merge them once stable. If the master branch is done and stable you can create a "release" The release will then have a version number.

The single commits don't since they might not be in historical order.

**Comment by echna** [comment]
I mean the numbering in this comment section doesn't work properly
1. This 
2. numbering
3. is
4. the one
5. I mean.

**Comment by gindeleo** [comment]
don't understand. Nevermind.

How can you still comment if the issue is closed ;)

**Comment by echna** [comment]
Actually, when posted it works, but not when looking at it in the editor.

More importantly, do you download the file, edit it and then upload it again? Or is there a more convenient way?

**Comment by echna** [comment]
I am god!

**Comment by gindeleo** [comment]
You forked your branch from the master one. Look at my develop one. I did clean the data.
